name: cms-hai-risk-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - xgboost
  - lightgbm
  - optuna        # For automated hyperparameter optimization
  - imbalanced-learn # For handling the 3.6% class imbalance (SMOTE)
  - joblib
  - jupyter
  - requests
  - pathlib
  - pyyaml